name: Run OpenAI Key Test

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use OpenAI API Key
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Your OpenAI API Key is: $OPENAI_API_KEY"
